In [1]:
import numpy as np
from scipy.sparse.linalg import eigs, eigsh

---

In [48]:
mat = np.load('./build/mat.npy')
v = np.load('./build/v.npy')
z = np.load('./build/z.npy')

In [49]:
mat.shape

(20, 20)

In [50]:
val, vec = eigsh(mat, which='SA')

In [51]:
val

array([-11.08658237,  -9.30788098,  -8.37053813,  -7.66785315,
        -6.03360495,  -5.2235537 ])

In [52]:
vec.shape

(20, 6)

In [53]:
v.shape

(11, 20)

In [54]:
z.shape

(5, 20)

In [55]:
zz = z.T
vv = v.T

In [56]:
zz.shape

(20, 5)

In [57]:
vec[:, 0]

array([ 0.20085961, -0.07944075,  0.09594667, -0.52560648,  0.30341857,
        0.02803882,  0.09206886, -0.03670221,  0.02176615, -0.19617004,
       -0.22682371,  0.20978223,  0.04811966,  0.14475389, -0.01164532,
        0.09539302, -0.16644396,  0.5847249 , -0.09210771,  0.14210782])

In [58]:
zz[:, 0]

array([ 0.20085961, -0.07944075,  0.09594667, -0.52560648,  0.30341857,
        0.02803882,  0.09206886, -0.03670221,  0.02176615, -0.19617004,
       -0.22682371,  0.20978223,  0.04811966,  0.14475389, -0.01164532,
        0.09539302, -0.16644396,  0.5847249 , -0.09210771,  0.14210782])

In [59]:
np.allclose(np.abs(zz), np.abs(vec[:, :5]))

True

In [60]:
vec[:, :5]

array([[ 0.20085961,  0.34798462, -0.06888834,  0.02259595, -0.23042008],
       [-0.07944075, -0.36863598,  0.26160182, -0.18286541,  0.07937888],
       [ 0.09594667,  0.27610118,  0.06180076, -0.58244608, -0.25890197],
       [-0.52560648, -0.05610194, -0.11857412,  0.01113821,  0.05874886],
       [ 0.30341857, -0.22342617, -0.08337484, -0.10051212,  0.41117734],
       [ 0.02803882,  0.02442228, -0.10309479, -0.03270065, -0.13225128],
       [ 0.09206886, -0.25087444, -0.38280004, -0.41159357,  0.05702956],
       [-0.03670221, -0.10935066, -0.10118654,  0.20137703, -0.08027574],
       [ 0.02176615, -0.25803577,  0.21660999,  0.10668038, -0.13409373],
       [-0.19617004, -0.41108613, -0.00897776, -0.25597759, -0.25935009],
       [-0.22682371,  0.13948551, -0.28163767,  0.16203543,  0.33908497],
       [ 0.20978223,  0.00532121, -0.27152568,  0.036027  ,  0.25449004],
       [ 0.04811966,  0.07343161, -0.46326259,  0.11625573,  0.02059089],
       [ 0.14475389, -0.13934764,  0.1

In [61]:
zz 

array([[ 0.20085961, -0.34798462,  0.06888834,  0.02259595,  0.23042008],
       [-0.07944075,  0.36863598, -0.26160182, -0.18286541, -0.07937888],
       [ 0.09594667, -0.27610118, -0.06180076, -0.58244608,  0.25890197],
       [-0.52560648,  0.05610194,  0.11857412,  0.01113821, -0.05874886],
       [ 0.30341857,  0.22342617,  0.08337484, -0.10051212, -0.41117734],
       [ 0.02803882, -0.02442228,  0.10309479, -0.03270065,  0.13225128],
       [ 0.09206886,  0.25087444,  0.38280004, -0.41159357, -0.05702956],
       [-0.03670221,  0.10935066,  0.10118654,  0.20137703,  0.08027574],
       [ 0.02176615,  0.25803577, -0.21660999,  0.10668038,  0.13409373],
       [-0.19617004,  0.41108613,  0.00897776, -0.25597759,  0.25935009],
       [-0.22682371, -0.13948551,  0.28163767,  0.16203543, -0.33908497],
       [ 0.20978223, -0.00532121,  0.27152568,  0.036027  , -0.25449004],
       [ 0.04811966, -0.07343161,  0.46326259,  0.11625573, -0.02059089],
       [ 0.14475389,  0.13934764, -0.1

In [62]:
vv[:, :5]

array([[ 0.20085961, -0.34798462,  0.06888834,  0.02259595,  0.23042008],
       [-0.07944075,  0.36863598, -0.26160182, -0.18286541, -0.07937888],
       [ 0.09594667, -0.27610118, -0.06180076, -0.58244608,  0.25890197],
       [-0.52560648,  0.05610194,  0.11857412,  0.01113821, -0.05874886],
       [ 0.30341857,  0.22342617,  0.08337484, -0.10051212, -0.41117734],
       [ 0.02803882, -0.02442228,  0.10309479, -0.03270065,  0.13225128],
       [ 0.09206886,  0.25087444,  0.38280004, -0.41159357, -0.05702956],
       [-0.03670221,  0.10935066,  0.10118654,  0.20137703,  0.08027574],
       [ 0.02176615,  0.25803577, -0.21660999,  0.10668038,  0.13409373],
       [-0.19617004,  0.41108613,  0.00897776, -0.25597759,  0.25935009],
       [-0.22682371, -0.13948551,  0.28163767,  0.16203543, -0.33908497],
       [ 0.20978223, -0.00532121,  0.27152568,  0.036027  , -0.25449004],
       [ 0.04811966, -0.07343161,  0.46326259,  0.11625573, -0.02059089],
       [ 0.14475389,  0.13934764, -0.1

In [67]:
mat = np.load('./build/double_m.npy')
cvec = np.load('./build/double_vec.npy')

In [68]:
val, vec = eigsh(mat, which = 'SA')

In [69]:
val

array([-11.08658237,  -9.30788098,  -8.37053813,  -7.66785315,
        -6.03360495,  -5.2235537 ])

In [77]:
for i, j in zip(vec.T, cvec.T):
    print(np.allclose(i, j*(i[0] / j[0])))

True
True
True
True
True
True


In [2]:
mat = np.load('./build/complex_m.npy')

In [3]:
np.allclose(mat, np.conj(mat).T)

True

In [4]:
#val, vec = eigsh(mat, which='SA')
val, vec = eigs(mat, which='SR')

In [5]:
val

array([-10.69144096+5.05094035e-16j,  -8.62753171+4.80264332e-17j,
        -4.95338376+1.55247420e-16j,  -3.02639176-1.75243267e-16j,
        -0.08293918+3.59574198e-16j,   1.0308716 -4.54052817e-16j])

In [8]:
mat1 = np.load('../debug/build/debug_double_mat.npy')
mat2 = np.load('../debug/build/debug_complex_mat.npy')

val1 = np.load('../debug/build/debug_double_val.npy')
val2 = np.load('../debug/build/debug_complex_val.npy')

vec1 = np.load('../debug/build/debug_double_vec.npy')
vec2 = np.load('../debug/build/debug_complex_vec.npy')

In [84]:
val, vec = eigsh(mat2, which='SA')

In [20]:
val

array([-37.70803661-7.39360446e-16j, -35.53251921-7.21314819e-16j,
       -33.77009387-7.27684878e-16j, -33.43882717-1.71736713e-15j,
       -31.9524652 -1.63411480e-16j, -30.75123817+5.05042498e-16j])

In [21]:
val2

array([-37.70803661, -35.53251921, -33.77009387, -33.43882717,
       -31.9524652 , -30.75123817])

In [22]:
np.allclose(mat2 @ vec, vec * val)

True

In [23]:
np.allclose(mat2 @ vec2, vec2 * val)

True

In [24]:
vec2[:, 0].conj() @ vec2[:, 0]

(0.9999999999999941+1.097671801350333e-19j)

In [25]:
vec[:, 0].conj() @ vec[:, 0]

(0.9999999999999993+6.938893903907228e-18j)

In [87]:
vec2[:, 0] / 

array([ 0.05691776+0.12338998j,  0.01429948-0.035328j  ,
       -0.08096255+0.00239097j,  0.01457326+0.06177318j,
       -0.11473929-0.00815556j, -0.05937574-0.12683988j,
       -0.04885711+0.02771655j, -0.03656883+0.1374721j ,
        0.07347212+0.07845476j, -0.05470591-0.00849429j,
       -0.08586264+0.04924193j, -0.09031979+0.02699483j,
       -0.0284282 -0.05931011j,  0.05672943+0.06855706j,
        0.10397347-0.08593061j,  0.02219661-0.12323645j,
       -0.0131216 -0.00710866j, -0.11971047-0.09338617j,
       -0.02362271+0.16509962j,  0.08559705-0.00978974j,
        0.02751463+0.11977123j,  0.03584951+0.01662022j,
       -0.05921968-0.0511843j , -0.0259551 +0.07853077j,
       -0.01346323+0.02835925j,  0.04906583+0.04392441j,
       -0.03522929+0.12132996j, -0.04591778+0.03431065j,
        0.06737629+0.06494943j,  0.00103733-0.04381604j,
       -0.07332036-0.00436811j,  0.02793507-0.09047111j,
       -0.07007168+0.00976438j, -0.12465373-0.01862225j,
       -0.06156399+0.16285412j,

In [31]:
vec[:, 0]

array([ 0.1160614 -0.07067156j, -0.03673294-0.01016039j,
        0.01164544+0.08015632j,  0.05969828-0.02155043j,
        0.0050357 +0.11491849j, -0.11920718+0.07350838j,
        0.03312839+0.04536225j,  0.14075511+0.0205878j ,
        0.06952624-0.08197197j, -0.00217461+0.05531872j,
        0.05874933+0.07965976j,  0.03715889+0.08663488j,
       -0.05566502+0.03503223j,  0.06161067-0.06420611j,
       -0.09727041-0.09345062j, -0.12496747-0.00794008j,
       -0.00555949+0.01384924j, -0.07906517+0.12961586j,
        0.1667186 +0.00456347j, -0.0195262 -0.08391317j,
        0.11583311-0.04104745j,  0.01240615-0.03751675j,
       -0.04406703+0.0646908j ,  0.08098615+0.01679264j,
        0.02971428+0.01012756j,  0.03801751-0.05377248j,
        0.12456575+0.02110534j,  0.03934257+0.04168723j,
        0.05680771-0.07436988j, -0.04364665+0.00398642j,
        0.00405578+0.0733383j , -0.09307467-0.01739242j,
        0.01772336+0.06849282j, -0.00422695+0.12596616j,
        0.16883214+0.04251234j,